<?php

class Rooster {

	public $classList = null;
	
	
	public $rooster = null;
	public $class = null;

	function __construct() {
		
	}
	
	function setClass($input) {
		if ($this->classList == null) {
			$classes = json_decode(file_get_contents(__DIR__ . "/../cache/classes.json"), true);
			if (!file_exists(__DIR__ . "/../cache/classes.json") || $classes["updated"] <= time() - 604800) { //1 week
				$classes = [
					"updated" => time(),
					"result"  => $this->getNewClasses()
				];
				file_put_contents(__DIR__ . "/../cache/classes.json", json_encode($classes));
			}
			
			$this->classList = $classes["result"];
		}
		
		if (in_array($input, $this->classList)) {
			$this->class = $input;
			return true;
		}
		return false;
	}
	
	function get() {
		if ($this->class == null) {
			die("Forgot to set a class");
		}
		
		if ($this->rooster == null) {
			$rooster = json_decode(file_get_contents(__DIR__ . "/../cache/roosters/".$this->class.".json"), true);
			if (!file_exists(__DIR__ . "/../cache/roosters/".$this->class.".json") || $rooster["updated"] <= time() - 86400) { //1 day
				$rooster = [
					"updated" => time(),
					"result"  => $this->getNewRooster(time(), time() + (604800 * 3))
				];
				file_put_contents(__DIR__ . "/../cache/roosters/".$this->class.".json", json_encode($rooster));
			}
			
			$this->rooster = $rooster["result"];
		}

		return $this->rooster;
	}
	
	function getNewClasses() {
	
		$classes = json_decode(file_get_contents("https://roosters.deltion.nl/api/group?".time()), true);
		return $classes["data"];
		
	}
	
	function getNewRooster($timeStart, $timeEnd) {
		$url = "https://roosters.deltion.nl/api/roster?group=".$this->class."&start=".date("Ymd", $timeStart)."&end=".date("Ymd", $timeEnd);

		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Authority: roosters.deltion.nl';
		$headers[] = 'Cache-Control: max-age=0';
		$headers[] = 'Upgrade-Insecure-Requests: 1';
		$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.79';
		$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8';
		$headers[] = 'Accept-Encoding: gzip, deflate, br';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = 'Cookie: DeltionID=9ReS9LNoe1Vi1gY9kCJ9SWqaWi';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$data = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close ($ch);

		$classes = json_decode($data, true);
		return $classes["data"];
	}

}